version: "4"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pzzld-bot
    depends_on:
      - cache
    environment:
      - OPENAI_API_TOKEN="${OPENAI_API_TOKEN}"
      - TELOXIDE_TOKEN="${TELOXIDE_TOKEN}"
    ports:
      - 8080:8080
      - 6379:6379
    restart: always
    tty: true
    volumes:
      - .config:/config
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

volumes:
  config:
  data:
